/**
 * IPL Teams section: loads /data/ipl-teams-bundle.json (generated by scripts/build-ipl-teams-bundle.mjs).
 */

const COLOR_PHRASES = {
  'navy blue': '#172554',
  'light blue': '#0ea5e9',
  'royal blue': '#2563eb',
};

function cssColorToken(raw) {
  if (!raw || typeof raw !== 'string') return '#475569';
  const key = raw.trim().toLowerCase();
  if (COLOR_PHRASES[key]) return COLOR_PHRASES[key];
  if (/\s/.test(key)) return '#1e293b';
  return key;
}

function gradientFromColors(colors) {
  if (!Array.isArray(colors) || colors.length === 0) {
    return 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #0f172a 100%)';
  }
  const [a, b] = colors;
  const c = cssColorToken(b || a);
  const d = cssColorToken(a);
  return `linear-gradient(135deg, ${d} 0%, ${c} 55%, #0f172a 100%)`;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Globally normalizes team names to fix common typos in the source data (e.g., Guiarat -> Gujarat).
 * Can be used on single names or blocks of text.
 */
function normalizeTeamText(text) {
  if (typeof text !== 'string' || !text) return text || '';
  return text
    .replace(/Guiarat/gi, 'Gujarat')
    .replace(/Raiasthan/gi, 'Rajasthan')
    .replace(/Puniab/gi, 'Punjab');
}

let selectedId = null;

function renderGrid(gridEl, teams, onSelect, gridOpts = {}) {
  const picker = Boolean(gridOpts.picker);
  gridEl.innerHTML = '';
  teams.forEach((team) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.setAttribute('role', picker ? 'option' : 'tab');
    btn.className = picker ? 'ipl-teams-card ipl-teams-card--picker' : 'ipl-teams-card';
    btn.dataset.teamId = team.id;
    const label = normalizeTeamText(team.name) || team.short_name || 'Team';
    btn.setAttribute('aria-label', label);
    btn.setAttribute(
      'aria-selected',
      selectedId != null && team.id === selectedId ? 'true' : 'false',
    );
    if (selectedId != null && team.id === selectedId) {
      btn.classList.add('ipl-teams-card--active');
    }

    const bgLayer = document.createElement('span');
    bgLayer.className = 'ipl-teams-card-bg';
    bgLayer.setAttribute('aria-hidden', 'true');
    if (team.bgUrl) {
      btn.classList.add('ipl-teams-card--has-photo-bg');
      bgLayer.style.backgroundImage = `url(${JSON.stringify(team.bgUrl)})`;
    } else {
      bgLayer.style.background = gradientFromColors(team.identity?.colors);
      btn.classList.add('ipl-teams-card--has-gradient-bg');
    }

    const scrim = document.createElement('span');
    scrim.className = 'ipl-teams-card-scrim';
    scrim.setAttribute('aria-hidden', 'true');

    const inner = document.createElement('span');
    inner.className = 'ipl-teams-card-inner';

    const wrap = document.createElement('span');
    wrap.className = 'ipl-teams-card-logo-wrap';
    if (team.logoUrl) {
      const img = document.createElement('img');
      img.src = team.logoUrl;
      img.alt = '';
      img.className = 'ipl-teams-card-logo';
      img.loading = 'lazy';
      img.decoding = 'async';
      wrap.appendChild(img);
    } else {
      const fb = document.createElement('span');
      fb.className = 'ipl-teams-card-fallback';
      fb.textContent = team.short_name || '';
      wrap.appendChild(fb);
    }

    const meta = document.createElement('span');
    meta.className = 'ipl-teams-card-meta';
    const name = document.createElement('span');
    name.className = 'ipl-teams-card-name';
    name.textContent = normalizeTeamText(team.name) || '';
    const abbr = document.createElement('span');
    abbr.className = 'ipl-teams-card-abbr';
    abbr.textContent = team.short_name || '';
    meta.append(name, abbr);

    inner.append(wrap, meta);
    const visual = document.createElement('span');
    visual.className = 'ipl-teams-card-visual';
    visual.setAttribute('aria-hidden', 'true');
    visual.append(bgLayer, scrim);
    btn.append(visual, inner);
    btn.addEventListener('click', () => {
      selectedId = team.id;
      gridEl.querySelectorAll('.ipl-teams-card').forEach((b) => {
        const active = b.dataset.teamId === selectedId;
        b.classList.toggle('ipl-teams-card--active', active);
        b.setAttribute('aria-selected', active ? 'true' : 'false');
      });
      // Switch to detail view mode
      document.body.classList.add('ipl-teams-showing-detail');
      window.scrollTo({ top: 0, behavior: 'smooth' });
      onSelect(team.id);
    });
    gridEl.appendChild(btn);
  });
}

function renderDetail(detailEl, team) {
  const bgStyle = team.bgUrl
    ? `background-image:url(${JSON.stringify(team.bgUrl)})`
    : `background:${gradientFromColors(team.identity?.colors)}`;
  const photoClass = team.bgUrl ? ' ipl-teams-detail-bg--photo' : '';

  const years =
    team.basic_info?.active_years?.length > 0
      ? `<span class="ipl-teams-badge ipl-teams-badge--muted">${escapeHtml(
          team.basic_info.active_years.join('–'),
        )}</span>`
      : '';

  const statusActive = team.basic_info?.status === 'active';
  const badgeClass = statusActive
    ? 'ipl-teams-badge ipl-teams-badge--active'
    : 'ipl-teams-badge ipl-teams-badge--defunct';
  const badgeLabel = statusActive ? 'Active' : 'Defunct';

  const chips =
    team.identity?.colors?.length > 0
      ? `<ul class="ipl-teams-chips" aria-label="Team colours">${team.identity.colors
          .map((c) => `<li class="ipl-teams-chip">${escapeHtml(c)}</li>`)
          .join('')}</ul>`
      : '';

  const honours = team.honours || {};
  const perf = team.performance?.overall;

  const titleYearPills =
    honours.title_years?.length > 0
      ? `<ul class="ipl-teams-title-year-pills" aria-label="IPL title years">${honours.title_years
          .map(
            (y) =>
              `<li class="ipl-teams-title-year-pill">${escapeHtml(String(y))}</li>`,
          )
          .join('')}</ul>`
      : '';

  const statBar =
    perf
      ? `<div class="ipl-teams-stat-bar" role="group" aria-label="Overall record stats">
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.matches ?? '—'))}</span>
          <span class="ipl-teams-stat-label">Matches</span>
        </div>
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.wins ?? '—'))}</span>
          <span class="ipl-teams-stat-label">Wins</span>
        </div>
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.win_pct ?? '—'))}${perf.win_pct != null ? '%' : ''}</span>
          <span class="ipl-teams-stat-label">Win %</span>
        </div>
      </div>`
      : '';

  const playerPills =
    team.notable_players?.length > 0
      ? `<ul class="ipl-teams-player-pills" aria-label="Notable players">${team.notable_players
          .map(
            (n) =>
              `<li class="ipl-teams-player-pill">${escapeHtml(n)}</li>`,
          )
          .join('')}</ul>`
      : '';

  const teamName = normalizeTeamText(team.name) || team.name || '';
  const finalHtml = normalizeTeamText(`
    <div class="ipl-teams-detail-hero">
      <div class="ipl-teams-detail-bg${photoClass}" style="${bgStyle}" aria-hidden="true"></div>
      <div class="ipl-teams-detail-scrim" aria-hidden="true"></div>
      
      <div class="ipl-teams-detail-header-row reveal">
        <div class="ipl-teams-detail-logo-wrap">
          <img src="${team.logoUrl || ''}" alt="" class="ipl-teams-detail-logo">
        </div>
        <div class="ipl-teams-detail-main">
          <div class="ipl-teams-detail-top-meta">
            <span class="ipl-teams-detail-abbr">${escapeHtml(team.short_name)}</span>
            ${years}
            <span class="ipl-teams-badge ipl-teams-badge--${team.basic_info?.status === 'active' ? 'success' : 'danger'}">
              ${escapeHtml(team.basic_info?.status || 'Active')}
            </span>
          </div>
          <h2 class="ipl-teams-detail-title">${escapeHtml(teamName)}</h2>
          <p class="ipl-teams-detail-location">${escapeHtml(team.basic_info?.city)}</p>
        </div>
      </div>
    </div>
    <div class="ipl-teams-detail-inner">
      ${
        team.identity?.meaning
          ? `<p class="ipl-teams-tagline">${escapeHtml(team.identity.meaning)}</p>`
          : ''
      }
      ${chips}
      <dl class="ipl-teams-facts">
        <div><dt>Captain</dt><dd>${escapeHtml(team.management?.captain ?? '—')}</dd></div>
        <div><dt>Coach</dt><dd>${escapeHtml(team.management?.coach ?? '—')}</dd></div>
        <div><dt>Founded</dt><dd>${escapeHtml(String(team.basic_info?.founded ?? '—'))}</dd></div>
        <div><dt>Owner</dt><dd>${escapeHtml(team.ownership?.current_owner ?? '—')}</dd></div>
      </dl>
      <div class="ipl-teams-block">
        <h4>Honours</h4>
        <p class="ipl-teams-honours-line">
          <strong>${escapeHtml(String(honours.ipl_titles ?? 0))}</strong> IPL titles
        </p>
        ${titleYearPills}
        <p class="ipl-teams-honours-meta">
          <strong>${escapeHtml(String(honours.finals ?? 0))}</strong> finals
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(honours.playoff_appearances ?? 0))}</strong> playoff runs
        </p>
      </div>
      ${
        perf
          ? `<div class="ipl-teams-block">
        <h4>Overall record</h4>
        ${statBar}
      </div>`
          : ''
      }
      <div class="ipl-teams-story">
        <h4>History</h4>
        <p>${escapeHtml(team.history?.full_text ?? '')}</p>
      </div>
      ${
        team.notable_players?.length
          ? `<div class="ipl-teams-block ipl-teams-block--players">
        <h4>Notable players</h4>
        ${playerPills}
      </div>`
          : ''
      }
    </div>
  `);

  detailEl.innerHTML = finalHtml;
}

/**
 * Resolve bundle JSON: always from site origin + `/data/...` so it works on Vercel
 * (avoid broken `import.meta.env.BASE_URL` values like `./`).
 */
function defaultBundleUrl() {
  if (typeof window !== 'undefined' && window.location?.origin) {
    return new URL('/data/ipl-teams-bundle.json', window.location.origin).href;
  }
  return '/data/ipl-teams-bundle.json';
}

async function fetchBundle(primaryUrl) {
  let res = await fetch(primaryUrl, { cache: 'no-store' });
  if (res.ok) return res;
  const fallback = new URL(
    'data/ipl-teams-bundle.json',
    window.location.href,
  ).href;
  if (fallback !== primaryUrl) {
    res = await fetch(fallback, { cache: 'no-store' });
  }
  return res;
}

/**
 * @param {object} [options]
 * @param {string} [options.bundleUrl] - override bundle location
 * @param {'split'|'fullscreen'} [options.layout] - fullscreen: icon grid then full-screen detail + Go back
 */
export async function initIplTeamsSection(options = {}) {
  const grid = document.getElementById('iplTeamsGrid');
  const detail = document.getElementById('iplTeamsDetail');
  const errEl = document.getElementById('iplTeamsError');
  const listStage = document.getElementById('iplTeamsListStage');
  const detailStage = document.getElementById('iplTeamsDetailStage');
  const stageBg = document.getElementById('iplTeamsStageBg');
  const backBtn = document.getElementById('iplTeamsBackBtn');
  if (!grid || !detail) return;

  const bundleUrl = options.bundleUrl ?? defaultBundleUrl();
  const useFullscreen =
    options.layout === 'fullscreen' && listStage && detailStage && backBtn;

  grid.innerHTML = '';
  grid.setAttribute('aria-busy', 'true');
  if (useFullscreen) {
    grid.setAttribute('aria-multiselectable', 'false');
  }
  const loadingEl = document.createElement('p');
  loadingEl.className = 'ipl-teams-loading';
  loadingEl.textContent = 'Loading teams…';
  grid.appendChild(loadingEl);
  detail.innerHTML = useFullscreen
    ? ''
    : '<p class="ipl-teams-detail-placeholder">Select a team to load details.</p>';

  function closeDetailView() {
    if (!useFullscreen) return;
    detailStage.hidden = true;
    listStage.hidden = false;
    if (stageBg) {
      stageBg.style.backgroundImage = '';
      stageBg.style.background = '';
    }
    document.body.classList.remove('ipl-teams-detail-open');
    const sel = selectedId
      ? [...grid.querySelectorAll('[data-team-id]')].find(
          (b) => b.dataset.teamId === selectedId,
        )
      : null;
    if (sel instanceof HTMLElement) sel.focus();
  }

  function openDetailView(team) {
    if (useFullscreen) {
      listStage.hidden = true;
      detailStage.hidden = false;
      if (stageBg) {
        if (team.bgUrl) {
          stageBg.style.backgroundImage = `url(${JSON.stringify(team.bgUrl)})`;
          stageBg.style.background = '';
        } else {
          stageBg.style.background = gradientFromColors(team.identity?.colors);
          stageBg.style.backgroundImage = '';
        }
      }
      document.body.classList.add('ipl-teams-detail-open');
    }
    renderDetail(detail, team);
    if (useFullscreen) {
      requestAnimationFrame(() => backBtn.focus());
      window.scrollTo({ top: 0, behavior: 'instant' });
    }
  }

  try {
    const res = await fetchBundle(bundleUrl);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    const data = await res.json();
    const teams = data.teams || [];
    if (!teams.length) throw new Error('No teams in bundle');

    selectedId = useFullscreen ? null : teams[0].id;

    renderGrid(
      grid,
      teams,
      (id) => {
        const t = teams.find((x) => x.id === id);
        if (t) openDetailView(t);
      },
      { picker: useFullscreen },
    );

    if (!useFullscreen) {
      renderDetail(detail, teams[0]);
    }

    if (useFullscreen) {
      backBtn.addEventListener('click', closeDetailView);
      document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && !detailStage.hidden) {
          e.preventDefault();
          closeDetailView();
        }
      });
    }

    if (errEl) {
      errEl.classList.add('hidden');
      errEl.textContent = '';
    }
  } catch (e) {
    console.error('[IPL Teams]', e);
    grid.innerHTML = '';
    detail.innerHTML = '';
    if (useFullscreen) {
      detailStage.hidden = true;
      document.body.classList.remove('ipl-teams-detail-open');
    }
    if (errEl) {
      errEl.textContent = `Could not load IPL team profiles (${e.message}).`;
      errEl.classList.remove('hidden');
    }
  } finally {
    grid.removeAttribute('aria-busy');
  }
}
