/**
 * IPL Teams section: loads /data/ipl-teams-bundle.json (generated by scripts/build-ipl-teams-bundle.mjs).
 */

const COLOR_PHRASES = {
  'navy blue': '#172554',
  'light blue': '#0ea5e9',
  'royal blue': '#2563eb',
};

function cssColorToken(raw) {
  if (!raw || typeof raw !== 'string') return '#475569';
  const key = raw.trim().toLowerCase();
  if (COLOR_PHRASES[key]) return COLOR_PHRASES[key];
  if (/\s/.test(key)) return '#1e293b';
  return key;
}

function gradientFromColors(colors) {
  if (!Array.isArray(colors) || colors.length === 0) {
    return 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #0f172a 100%)';
  }
  const [a, b] = colors;
  const c = cssColorToken(b || a);
  const d = cssColorToken(a);
  return `linear-gradient(135deg, ${d} 0%, ${c} 55%, #0f172a 100%)`;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

let selectedId = null;

function renderGrid(gridEl, teams, onSelect) {
  gridEl.innerHTML = '';
  teams.forEach((team) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.setAttribute('role', 'tab');
    btn.className = 'ipl-teams-card';
    btn.dataset.teamId = team.id;
    btn.setAttribute('aria-selected', team.id === selectedId ? 'true' : 'false');
    if (team.id === selectedId) btn.classList.add('ipl-teams-card--active');

    const bgLayer = document.createElement('span');
    bgLayer.className = 'ipl-teams-card-bg';
    bgLayer.setAttribute('aria-hidden', 'true');
    if (team.bgUrl) {
      btn.classList.add('ipl-teams-card--has-photo-bg');
      bgLayer.style.backgroundImage = `url(${JSON.stringify(team.bgUrl)})`;
    } else {
      bgLayer.style.background = gradientFromColors(team.identity?.colors);
      btn.classList.add('ipl-teams-card--has-gradient-bg');
    }

    const scrim = document.createElement('span');
    scrim.className = 'ipl-teams-card-scrim';
    scrim.setAttribute('aria-hidden', 'true');

    const inner = document.createElement('span');
    inner.className = 'ipl-teams-card-inner';

    const wrap = document.createElement('span');
    wrap.className = 'ipl-teams-card-logo-wrap';
    if (team.logoUrl) {
      const img = document.createElement('img');
      img.src = team.logoUrl;
      img.alt = '';
      img.className = 'ipl-teams-card-logo';
      img.loading = 'lazy';
      img.decoding = 'async';
      wrap.appendChild(img);
    } else {
      const fb = document.createElement('span');
      fb.className = 'ipl-teams-card-fallback';
      fb.textContent = team.short_name || '';
      wrap.appendChild(fb);
    }

    const meta = document.createElement('span');
    meta.className = 'ipl-teams-card-meta';
    const name = document.createElement('span');
    name.className = 'ipl-teams-card-name';
    name.textContent = team.name || '';
    const abbr = document.createElement('span');
    abbr.className = 'ipl-teams-card-abbr';
    abbr.textContent = team.short_name || '';
    meta.append(name, abbr);

    inner.append(wrap, meta);
    btn.append(bgLayer, scrim, inner);
    btn.addEventListener('click', () => {
      selectedId = team.id;
      gridEl.querySelectorAll('.ipl-teams-card').forEach((b) => {
        const active = b.dataset.teamId === selectedId;
        b.classList.toggle('ipl-teams-card--active', active);
        b.setAttribute('aria-selected', active ? 'true' : 'false');
      });
      onSelect(team.id);
    });
    gridEl.appendChild(btn);
  });
}

function renderDetail(detailEl, team) {
  const bgStyle = team.bgUrl
    ? `background-image:url(${JSON.stringify(team.bgUrl)})`
    : `background:${gradientFromColors(team.identity?.colors)}`;
  const photoClass = team.bgUrl ? ' ipl-teams-detail-bg--photo' : '';

  const years =
    team.basic_info?.active_years?.length > 0
      ? `<span class="ipl-teams-badge ipl-teams-badge--muted">${escapeHtml(
          team.basic_info.active_years.join('–'),
        )}</span>`
      : '';

  const statusActive = team.basic_info?.status === 'active';
  const badgeClass = statusActive
    ? 'ipl-teams-badge ipl-teams-badge--active'
    : 'ipl-teams-badge ipl-teams-badge--defunct';
  const badgeLabel = statusActive ? 'Active' : 'Defunct';

  const chips =
    team.identity?.colors?.length > 0
      ? `<ul class="ipl-teams-chips" aria-label="Team colours">${team.identity.colors
          .map((c) => `<li class="ipl-teams-chip">${escapeHtml(c)}</li>`)
          .join('')}</ul>`
      : '';

  const honours = team.honours || {};
  const perf = team.performance?.overall;

  detailEl.innerHTML = `
    <div class="ipl-teams-detail-bg${photoClass}" style="${bgStyle}" aria-hidden="true"></div>
    <div class="ipl-teams-detail-scrim" aria-hidden="true"></div>
    <div class="ipl-teams-detail-inner">
      <header class="ipl-teams-detail-head">
        ${
          team.logoUrl
            ? `<img src=${JSON.stringify(team.logoUrl)} alt="" class="ipl-teams-detail-logo" width="96" height="96" />`
            : ''
        }
        <div class="ipl-teams-detail-titles">
          <h3 class="ipl-teams-detail-title">${escapeHtml(team.name)}</h3>
          <p class="ipl-teams-detail-sub">
            <strong>${escapeHtml(team.short_name)}</strong>
            <span class="ipl-teams-dot" aria-hidden="true">·</span>
            ${escapeHtml(team.basic_info?.city ?? '')}
          </p>
          <div class="ipl-teams-badges">
            <span class="${badgeClass}">${badgeLabel}</span>
            ${years}
          </div>
        </div>
      </header>
      ${
        team.identity?.meaning
          ? `<p class="ipl-teams-tagline">${escapeHtml(team.identity.meaning)}</p>`
          : ''
      }
      ${chips}
      <dl class="ipl-teams-facts">
        <div><dt>Captain</dt><dd>${escapeHtml(team.management?.captain ?? '—')}</dd></div>
        <div><dt>Coach</dt><dd>${escapeHtml(team.management?.coach ?? '—')}</dd></div>
        <div><dt>Founded</dt><dd>${escapeHtml(String(team.basic_info?.founded ?? '—'))}</dd></div>
        <div><dt>Owner</dt><dd>${escapeHtml(team.ownership?.current_owner ?? '—')}</dd></div>
      </dl>
      <div class="ipl-teams-block">
        <h4>Honours</h4>
        <p>
          <strong>${escapeHtml(String(honours.ipl_titles ?? 0))}</strong> titles
          ${
            honours.title_years?.length
              ? ` (${honours.title_years.map((y) => escapeHtml(String(y))).join(', ')})`
              : ''
          }
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(honours.finals ?? 0))}</strong> finals
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(honours.playoff_appearances ?? 0))}</strong> playoff runs
        </p>
      </div>
      ${
        perf
          ? `<div class="ipl-teams-block">
        <h4>Overall record</h4>
        <p>
          <strong>${escapeHtml(String(perf.matches))}</strong> matches
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(perf.wins))}</strong> wins
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(perf.win_pct))}%</strong> win rate
        </p>
      </div>`
          : ''
      }
      <div class="ipl-teams-story">
        <h4>History</h4>
        <p>${escapeHtml(team.history?.full_text ?? '')}</p>
      </div>
      ${
        team.notable_players?.length
          ? `<div class="ipl-teams-block">
        <h4>Notable players</h4>
        <p class="ipl-teams-players">${escapeHtml(team.notable_players.join(', '))}</p>
      </div>`
          : ''
      }
    </div>
  `;
}

/**
 * @param {object} [options]
 * @param {string} [options.bundleUrl] - defaults to site-root data path (works with Vite base)
 */
export async function initIplTeamsSection(options = {}) {
  const grid = document.getElementById('iplTeamsGrid');
  const detail = document.getElementById('iplTeamsDetail');
  const errEl = document.getElementById('iplTeamsError');
  if (!grid || !detail) return;

  const base = typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL
    ? import.meta.env.BASE_URL
    : '/';
  const prefix = base === '/' ? '/' : base.replace(/\/?$/, '/');
  const bundleUrl =
    options.bundleUrl ??
    (prefix === '/' ? '/data/ipl-teams-bundle.json' : `${prefix}data/ipl-teams-bundle.json`);

  try {
    const res = await fetch(bundleUrl);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    const data = await res.json();
    const teams = data.teams || [];
    if (!teams.length) throw new Error('No teams in bundle');

    selectedId = teams[0].id;
    renderGrid(grid, teams, (id) => {
      const t = teams.find((x) => x.id === id);
      if (t) renderDetail(detail, t);
    });
    renderDetail(detail, teams[0]);
    if (errEl) {
      errEl.classList.add('hidden');
      errEl.textContent = '';
    }
  } catch (e) {
    console.error('[IPL Teams]', e);
    if (errEl) {
      errEl.textContent = `Could not load IPL team profiles (${e.message}). Run the site from the Vite dev server or rebuild so /data/ipl-teams-bundle.json is available.`;
      errEl.classList.remove('hidden');
    }
  }
}
