/**
 * IPL Teams section: loads /data/ipl-teams-bundle.json (generated by scripts/build-ipl-teams-bundle.mjs).
 */

const COLOR_PHRASES = {
  'navy blue': '#172554',
  'light blue': '#0ea5e9',
  'royal blue': '#2563eb',
};

function cssColorToken(raw) {
  if (!raw || typeof raw !== 'string') return '#475569';
  const key = raw.trim().toLowerCase();
  if (COLOR_PHRASES[key]) return COLOR_PHRASES[key];
  if (/\s/.test(key)) return '#1e293b';
  return key;
}

function gradientFromColors(colors) {
  if (!Array.isArray(colors) || colors.length === 0) {
    return 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #0f172a 100%)';
  }
  const [a, b] = colors;
  const c = cssColorToken(b || a);
  const d = cssColorToken(a);
  return `linear-gradient(135deg, ${d} 0%, ${c} 55%, #0f172a 100%)`;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Globally normalizes team names to fix common typos in the source data (e.g., Guiarat -> Gujarat).
 * Can be used on single names or blocks of text.
 */
function normalizeTeamText(text) {
  if (typeof text !== 'string' || !text) return text || '';
  return text
    .replace(/Guiarat/gi, 'Gujarat')
    .replace(/Raiasthan/gi, 'Rajasthan')
    .replace(/Puniab/gi, 'Punjab');
}

let selectedId = null;

function renderGrid(gridEl, teams, onSelect, gridOpts = {}) {
  const picker = Boolean(gridOpts.picker);
  gridEl.innerHTML = '';
  teams.forEach((team) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.setAttribute('role', picker ? 'option' : 'tab');
    btn.className = picker ? 'ipl-teams-card ipl-teams-card--picker' : 'ipl-teams-card';
    btn.dataset.teamId = team.id;
    const label = normalizeTeamText(team.name) || team.short_name || 'Team';
    btn.setAttribute('aria-label', label);
    btn.setAttribute(
      'aria-selected',
      selectedId != null && team.id === selectedId ? 'true' : 'false',
    );
    if (selectedId != null && team.id === selectedId) {
      btn.classList.add('ipl-teams-card--active');
    }

    const bgLayer = document.createElement('span');
    bgLayer.className = 'ipl-teams-card-bg';
    bgLayer.setAttribute('aria-hidden', 'true');
    if (team.bgUrl) {
      btn.classList.add('ipl-teams-card--has-photo-bg');
      bgLayer.style.backgroundImage = `url(${JSON.stringify(team.bgUrl)})`;
    } else {
      bgLayer.style.background = gradientFromColors(team.identity?.colors);
      btn.classList.add('ipl-teams-card--has-gradient-bg');
    }

    const scrim = document.createElement('span');
    scrim.className = 'ipl-teams-card-scrim';
    scrim.setAttribute('aria-hidden', 'true');

    const inner = document.createElement('span');
    inner.className = 'ipl-teams-card-inner';

    const wrap = document.createElement('span');
    wrap.className = 'ipl-teams-card-logo-wrap';
    if (team.logoUrl) {
      const img = document.createElement('img');
      img.src = team.logoUrl;
      img.alt = '';
      img.className = 'ipl-teams-card-logo';
      img.loading = 'lazy';
      img.decoding = 'async';
      wrap.appendChild(img);
    } else {
      const fb = document.createElement('span');
      fb.className = 'ipl-teams-card-fallback';
      fb.textContent = team.short_name || '';
      wrap.appendChild(fb);
    }

    const meta = document.createElement('span');
    meta.className = 'ipl-teams-card-meta';
    
    // Add Sparkline Canvas
    const sparkWrap = document.createElement('div');
    sparkWrap.className = 'ipl-teams-card-spark-wrap';
    sparkWrap.innerHTML = `<canvas id="spark-${team.id}" class="team-sparkline" width="100" height="30"></canvas>`;
    
    const name = document.createElement('span');
    name.className = 'ipl-teams-card-name';
    name.textContent = normalizeTeamText(team.name) || '';
    const abbr = document.createElement('span');
    abbr.className = 'ipl-teams-card-abbr';
    abbr.textContent = team.short_name || '';
    meta.append(sparkWrap, name, abbr);

    inner.append(wrap, meta);
    const visual = document.createElement('span');
    visual.className = 'ipl-teams-card-visual';
    visual.setAttribute('aria-hidden', 'true');
    visual.append(bgLayer, scrim);
    btn.append(visual, inner);
    btn.addEventListener('click', () => {
      selectedId = team.id;
      gridEl.querySelectorAll('.ipl-teams-card').forEach((b) => {
        const active = b.dataset.teamId === selectedId;
        b.classList.toggle('ipl-teams-card--active', active);
        b.setAttribute('aria-selected', active ? 'true' : 'false');
      });
      onSelect(team.id);
    });
    gridEl.appendChild(btn);
  });

  // After grid is rendered, populate sparklines
  requestAnimationFrame(() => {
    teams.forEach(team => {
      const canvas = document.getElementById(`spark-${team.id}`);
      if (canvas) {
        // Generate unique historical trajectories for major teams
        const mockData = {
          'csk': [2, 1, 2, 1, 4, 1, 2, 9, 1, 2], // Consistent top finisher
          'mi': [7, 3, 1, 4, 1, 1, 5, 1, 10, 4], // Boom and bust dynasty
          'rcb': [7, 2, 4, 5, 2, 8, 3, 4, 6, 4], // The 'Always Close' trend
          'kkr': [6, 8, 4, 1, 7, 1, 5, 2, 7, 1], // The comeback kings
          'srh': [1, 4, 3, 2, 1, 4, 3, 8, 10, 2], // Mid-era dominance
          'rr': [1, 6, 7, 7, 3, 6, 4, 7, 2, 5], // The underdog path
          'gt': [1, 2, 8], // The new power surge
          'lsg': [3, 4, 7]  // Consistent playoff contender
        };
        const ranks = mockData[team.id] || [4, 8, 3, 5, 2, 7, 5, 3];

        new Chart(canvas.getContext('2d'), {
          type: 'line',
          data: {
            labels: ranks.map((_, i) => i),
            datasets: [{
              data: ranks,
              borderColor: 'rgba(128, 92, 230, 0.4)',
              borderWidth: 1.5,
              pointRadius: 0,
              fill: false,
              tension: 0.4
            }]
          },
          options: {
            responsive: false,
            maintainAspectRatio: false,
            scales: { x: { display: false }, y: { display: false, reverse: true } },
            plugins: { legend: { display: false }, tooltip: { enabled: false } }
          }
        });
      }
    });
  });
}

function renderDetail(detailEl, team, xaiHtml = "") {
  const bgStyle = team.bgUrl
    ? `background-image:url(${JSON.stringify(team.bgUrl)})`
    : `background:${gradientFromColors(team.identity?.colors)}`;
  const photoClass = team.bgUrl ? ' ipl-teams-detail-bg--photo' : '';

  const years =
    team.basic_info?.active_years?.length > 0
      ? `<span class="ipl-teams-badge ipl-teams-badge--muted">${escapeHtml(
          team.basic_info.active_years.join('–'),
        )}</span>`
      : '';

  const statusActive = team.basic_info?.status === 'active';
  const badgeClass = statusActive
    ? 'ipl-teams-badge ipl-teams-badge--active'
    : 'ipl-teams-badge ipl-teams-badge--defunct';
  const badgeLabel = statusActive ? 'Active' : 'Defunct';

  const chips =
    team.identity?.colors?.length > 0
      ? `<ul class="ipl-teams-chips" aria-label="Team colours">${team.identity.colors
          .map((c) => `<li class="ipl-teams-chip">${escapeHtml(c)}</li>`)
          .join('')}</ul>`
      : '';

  const honours = team.honours || {};
  const perf = team.performance?.overall;

  const titleYearPills =
    honours.title_years?.length > 0
      ? `<ul class="ipl-teams-title-year-pills" aria-label="IPL title years">${honours.title_years
          .map(
            (y) =>
              `<li class="ipl-teams-title-year-pill">${escapeHtml(String(y))}</li>`,
          )
          .join('')}</ul>`
      : '';

  const statBar =
    perf
      ? `<div class="ipl-teams-stat-bar" role="group" aria-label="Overall record stats">
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.matches ?? '—'))}</span>
          <span class="ipl-teams-stat-label">Matches</span>
        </div>
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.wins ?? '—'))}</span>
          <span class="ipl-teams-stat-label">Wins</span>
        </div>
        <div class="ipl-teams-stat-block">
          <span class="ipl-teams-stat-value">${escapeHtml(String(perf.win_pct ?? '—'))}${perf.win_pct != null ? '%' : ''}</span>
          <span class="ipl-teams-stat-label">Win %</span>
        </div>
      </div>`
      : '';

  const playerPills =
    team.notable_players?.length > 0
      ? `<ul class="ipl-teams-player-pills" aria-label="Notable players">${team.notable_players
          .map(
            (n) =>
              `<li class="ipl-teams-player-pill">${escapeHtml(n)}</li>`,
          )
        .join('')}</ul>`
      : '';

  const socialLinks = team.social_links;
  let socialHtml = '';
  if (socialLinks) {
    socialHtml = '<div class="ipl-teams-social-row">';
    const icons = {
      twitter: 'fa-x-twitter',
      instagram: 'fa-instagram',
      facebook: 'fa-facebook',
      youtube: 'fa-youtube',
      website: 'fa-globe'
    };
    
    Object.entries(socialLinks).forEach(([key, url]) => {
      if (url && icons[key]) {
        const iconClass = key === 'website' ? `fa-solid ${icons[key]}` : `fa-brands ${icons[key]}`;
        socialHtml += `
          <a href="${escapeHtml(url)}" target="_blank" class="ipl-teams-social-link" title="${key.charAt(0).toUpperCase() + key.slice(1)}">
            <i class="${iconClass}"></i>
          </a>`;
      }
    });
    socialHtml += '</div>';
  }


  // Quality color map for IPL identities
  const teamColorMap = {
    csk: '#FDB913', // Classic CSK Yellow
    mi: '#004BA0',  // Mumbai Blue
    rcb: '#ED1B24', // RCB Red
    kkr: '#3A225D', // KKR Purple
    srh: '#FF822A', // SRH Orange
    rr: '#EA1A85',  // RR Pink
    dc: '#00008B',  // DC Blue
    pbks: '#D31A24', // Punjab Red
    gt: '#1B2133',  // GT Navy Blue
    lsg: '#00ADEF', // LSG Light Blue
    dcg: '#004BA0', // Deccan Blue
    pwi: '#2E3192', // Pune Warriors Blue
    ktk: '#FDB913', // Kochi Gold
    rps: '#4B2682', // RPS Purple
    gl: '#C1272D'   // Lions Orange-Red
  };

  const teamPrimaryColor = teamColorMap[team.id] || '#8b5cf6';
  const titles = honours.ipl_titles || 0;
  const winPct = perf?.win_pct || 0;

  let narrativeStr = "Competitive Franchise";
  if (titles >= 3) narrativeStr = "Legendary Dynasty";
  else if (titles > 0) narrativeStr = "Proven Champion";
  else if (winPct > 50) narrativeStr = "Strategic Heavyweight";
  else narrativeStr = "Market Challenger";

  const teamName = normalizeTeamText(team.name) || team.name || '';
  const squadListUrl = `./squad-list.html?team=${encodeURIComponent(team.id || '')}&name=${encodeURIComponent(teamName)}&bg=${encodeURIComponent(team.bgUrl || '')}`;
  const finalHtml = normalizeTeamText(`
    <div class="ipl-teams-detail-inner" style="--team-glow: ${teamPrimaryColor}">
      <div class="ipl-teams-detail-bg-glow"></div>
      <header class="ipl-teams-detail-head">
        <div class="ipl-teams-detail-logo-pod">
          <img src="${team.logoUrl || ''}" alt="" class="ipl-teams-detail-logo">
        </div>
        <div class="ipl-teams-detail-titling">
          <div class="ipl-teams-detail-top-meta">
            <span class="ipl-teams-badge ipl-teams-badge--strategic">${narrativeStr}</span>
            <span class="ipl-teams-dot"> · </span>
            <span class="ipl-teams-detail-abbr">${escapeHtml(team.short_name)}</span>
            <span class="ipl-teams-dot"> · </span>
            <span class="ipl-teams-badge ipl-teams-badge--${team.basic_info?.status === 'active' ? 'success' : 'danger'}">
              ${escapeHtml(team.basic_info?.status || 'Active')}
            </span>
          </div>
          <h2 class="ipl-teams-detail-title">${escapeHtml(teamName)}</h2>
          <p class="ipl-teams-detail-sub">
            ${escapeHtml(team.basic_info?.city)}
            <span class="ipl-teams-dot"> · </span>
            Since <strong>${escapeHtml(String(team.basic_info?.founded))}</strong>
          </p>
          <div class="ipl-teams-detail-actions">
            <a href="${squadListUrl}" class="ipl-teams-squad-link">Squads List</a>
          </div>
          ${socialHtml}
        </div>
      </header>

      <div class="ipl-teams-detail-tagline-row">
        ${team.identity?.meaning ? `<p class="ipl-teams-tagline">${escapeHtml(team.identity.meaning)}</p>` : ''}
        ${chips}
      </div>

      <dl class="ipl-teams-facts">
        <div><dt>Captain</dt><dd>${escapeHtml(team.management?.captain ?? '—')}</dd></div>
        <div><dt>Coach</dt><dd>${escapeHtml(team.management?.coach ?? '—')}</dd></div>
        <div><dt>Founded</dt><dd>${escapeHtml(String(team.basic_info?.founded ?? '—'))}</dd></div>
        <div><dt>Owner</dt><dd>${escapeHtml(team.ownership?.current_owner ?? '—')}</dd></div>
      </dl>
      <div class="ipl-teams-block">
        <h4>Honours</h4>
        <p class="ipl-teams-honours-line">
          <strong>${escapeHtml(String(honours.ipl_titles ?? 0))}</strong> IPL titles
        </p>
        ${titleYearPills}
        <p class="ipl-teams-honours-meta">
          <strong>${escapeHtml(String(honours.finals ?? 0))}</strong> finals
          <span class="ipl-teams-dot"> · </span>
          <strong>${escapeHtml(String(honours.playoff_appearances ?? 0))}</strong> playoff runs
        </p>
      </div>

      <div class="ipl-teams-grid-sections">
        <div class="ipl-teams-block">
          <h4>Home Grounds</h4>
          <ul class="ipl-teams-list">
            ${(team.home_grounds || []).map(g => `
              <li>
                <strong>${escapeHtml(g.name)}</strong> (${escapeHtml(g.location)})
                ${g.primary ? '<span class="ipl-teams-badge ipl-teams-badge--tiny">Primary</span>' : ''}
              </li>
            `).join('')}
          </ul>
        </div>

        <div class="ipl-teams-block">
          <h4>Notable Captains</h4>
          <ul class="ipl-teams-list">
            ${(team.management?.notable_captains || []).map(c => `<li>${escapeHtml(c)}</li>`).join('')}
          </ul>
        </div>

        <div class="ipl-teams-block">
          <h4>Notable Coaches</h4>
          <ul class="ipl-teams-list">
            ${(team.management?.notable_coaches || []).map(c => `<li>${escapeHtml(c)}</li>`).join('')}
          </ul>
        </div>
      </div>

      ${
        perf
          ? `<div class="ipl-teams-block">
        <h4>Overall record</h4>
        ${statBar}
      </div>`
          : ''
      }

      <div class="ipl-teams-grid-sections">
        <div class="ipl-teams-block">
          <h4>Strengths</h4>
          <ul class="ipl-teams-list ipl-teams-list--checks">
            ${(team.performance?.strengths || []).map(s => `<li>${escapeHtml(s)}</li>`).join('')}
          </ul>
        </div>
        <div class="ipl-teams-block">
          <h4>Weaknesses</h4>
          <ul class="ipl-teams-list ipl-teams-list--crosses">
            ${(team.performance?.weaknesses || []).map(w => `<li>${escapeHtml(w)}</li>`).join('')}
          </ul>
        </div>
      </div>

      <div class="ipl-teams-story">
        <h4>History</h4>
        <div class="ipl-teams-story-text">${normalizeTeamText(team.history?.full_text ?? '').split('. ').map(s => s.trim() ? `<p>${escapeHtml(s.trim())}${s.trim().endsWith('.') ? '' : '.'}</p>` : '').join('')}</div>
      </div>

      ${team.history?.timeline ? `
        <div class="ipl-teams-block">
          <h4>Timeline</h4>
          <div class="ipl-teams-timeline">
            ${team.history.timeline.map(item => {
              const [year, ...txt] = item.split(': ');
              return `
                <div class="ipl-teams-timeline-item">
                  <span class="ipl-teams-timeline-year">${escapeHtml(year)}</span>
                  <span class="ipl-teams-timeline-text">${escapeHtml(txt.join(': '))}</span>
                </div>
              `;
            }).join('')}
          </div>
        </div>
      ` : ''}

      ${team.rivalries?.length ? `
        <div class="ipl-teams-block">
          <h4>Key Rivalries</h4>
          <div class="ipl-teams-rivalries">
            ${team.rivalries.map(r => `
              <div class="ipl-teams-rivalry-card">
                <h5>${escapeHtml(r.team)}</h5>
                <p>${escapeHtml(r.details)}</p>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      ${team.intelligence ? `
        <div class="ipl-teams-intel-section">
          <div class="ipl-teams-block ipl-teams-block--intel">
            <h4><i class="fa-solid fa-brain"></i> Team Intelligence Briefing</h4>
            <div class="ipl-teams-intel-tag">
              <span class="ipl-teams-badge ipl-teams-badge--strategic">${team.intelligence.archetype}</span>
              <p class="ipl-teams-intel-insight">${team.intelligence.insight}</p>
              ${xaiHtml}
            </div>
          </div>

          <div class="ipl-teams-grid-sections">
            <div class="ipl-teams-block">
              <h4>📊 Performance Insights</h4>
              <dl class="ipl-teams-facts ipl-teams-facts--grid">
                <div><dt>Best Season</dt><dd>${team.intelligence.performance.best_season}</dd></div>
                <div><dt>Worst Season</dt><dd>${team.intelligence.performance.worst_season}</dd></div>
                <div><dt>Avg Finish</dt><dd>${team.intelligence.performance.avg_finish}</dd></div>
                <div><dt>Playoff Rate</dt><dd>${team.intelligence.performance.playoff_rate}%</dd></div>
              </dl>
            </div>

            <div class="ipl-teams-block">
              <h4>💰 Auction DNA</h4>
               <dl class="ipl-teams-facts ipl-teams-facts--grid">
                <div><dt>Strategy</dt><dd>${team.intelligence.auction_dna.strategy}</dd></div>
                <div><dt>Top Buy</dt><dd>${team.intelligence.auction_dna.highest_buy}</dd></div>
                <div><dt>Value King</dt><dd>${team.intelligence.auction_dna.best_value}</dd></div>
                <div><dt>Avg Spend</dt><dd>₹${team.intelligence.auction_dna.avg_spend_per_season} Cr</dd></div>
              </dl>
            </div>
          </div>

          <div class="ipl-teams-block">
            <h4>🏆 Record Holders</h4>
            <div class="ipl-teams-stat-bar">
              <div class="ipl-teams-stat-block">
                <span class="ipl-teams-stat-label">Most Runs</span>
                <span class="ipl-teams-stat-value ipl-teams-stat-value--small">${team.intelligence.records.most_runs}</span>
              </div>
              <div class="ipl-teams-stat-block">
                <span class="ipl-teams-stat-label">Most Wickets</span>
                <span class="ipl-teams-stat-value ipl-teams-stat-value--small">${team.intelligence.records.most_wickets}</span>
              </div>
            </div>
          </div>
        </div>
      ` : ''}

      ${
        team.notable_players?.length
          ? `<div class="ipl-teams-block ipl-teams-block--players">
        <h4>Notable players</h4>
        ${playerPills}
      </div>`
          : ''
      }
    </div>
  `);

  detailEl.innerHTML = finalHtml;
}

/**
 * Resolve bundle JSON: always from site origin + `/data/...` so it works on Vercel
 * (avoid broken `import.meta.env.BASE_URL` values like `./`).
 */
function defaultBundleUrl() {
  if (typeof window !== 'undefined' && window.location?.origin) {
    return new URL('./public/data/ipl-teams-bundle.json', window.location.origin).href;
  }
  return './public/data/ipl-teams-bundle.json';
}

async function fetchBundle(primaryUrl) {
  let res = await fetch(primaryUrl, { cache: 'no-store' });
  if (res.ok) return res;
  const fallback = new URL(
    'data/ipl-teams-bundle.json',
    window.location.href,
  ).href;
  if (fallback !== primaryUrl) {
    res = await fetch(fallback, { cache: 'no-store' });
  }
  return res;
}

/**
 * @param {object} [options]
 * @param {string} [options.bundleUrl] - override bundle location
 * @param {'split'|'fullscreen'} [options.layout] - fullscreen: icon grid then full-screen detail + Go back
 */
export async function initIplTeamsSection(options = {}) {
  const grid = document.getElementById('iplTeamsGrid');
  const detail = document.getElementById('iplTeamsDetail');
  const errEl = document.getElementById('iplTeamsError');
  const listStage = document.getElementById('iplTeamsListStage');
  const detailStage = document.getElementById('iplTeamsDetailStage');
  const stageBg = document.getElementById('iplTeamsStageBg');
  const backBtn = document.getElementById('iplTeamsBackBtn');
  if (!grid || !detail) return;

  const bundleUrl = options.bundleUrl ?? defaultBundleUrl();
  const useFullscreen =
    options.layout === 'fullscreen' && listStage && detailStage && backBtn;

  let teamXAI = {};
  function createXAICard(data) {
    if (!data || !data.label) return "";
    const confClass = `conf-${String(data.confidence).toLowerCase()}`;
    return `
      <div class="xai-card" style="margin-top: 1.5rem; background: rgba(139, 92, 246, 0.03); border-color: rgba(139, 92, 246, 0.3);">
        <div class="xai-header">🧠 Strategic Intelligence Insight</div>
        <div class="xai-label">${data.label}</div>
        <div class="xai-header">📊 Data-Backed Reasoning</div>
        <div class="xai-reason-item">
          <div class="xai-reason-text">${data.reason}</div>
        </div>
        <div class="xai-confidence-wrap" style="border-top: 1px solid rgba(255,255,255,0.05); padding-top: 10px;">
          ⚡ Confidence: <span class="${confClass}">${data.confidence}</span>
        </div>
      </div>
    `;
  }

  grid.innerHTML = '';
  grid.setAttribute('aria-busy', 'true');
  if (useFullscreen) {
    grid.setAttribute('aria-multiselectable', 'false');
  }
  const loadingEl = document.createElement('p');
  loadingEl.className = 'ipl-teams-loading';
  loadingEl.textContent = 'Loading teams…';
  grid.appendChild(loadingEl);
  detail.innerHTML = useFullscreen
    ? ''
    : '<p class="ipl-teams-detail-placeholder">Select a team to load details.</p>';

  function closeDetailView() {
    if (!useFullscreen) return;
    detailStage.hidden = true;
    listStage.hidden = false;
    if (stageBg) {
      stageBg.style.backgroundImage = '';
      stageBg.style.background = '';
    }
    document.body.classList.remove('ipl-teams-detail-open');
    const sel = selectedId
      ? [...grid.querySelectorAll('[data-team-id]')].find(
          (b) => b.dataset.teamId === selectedId,
        )
      : null;
    if (sel instanceof HTMLElement) sel.focus();
  }

  function openDetailView(team) {
    if (useFullscreen) {
      listStage.hidden = true;
      detailStage.hidden = false;
      if (stageBg) {
        if (team.bgUrl) {
          stageBg.style.backgroundImage = "url('" + team.bgUrl + "')";
          if (detailStage) detailStage.style.backgroundColor = 'transparent';
        } else {
          stageBg.style.backgroundImage = 'none';
          if (detailStage) detailStage.style.backgroundColor = '#06080c';
        }
      }
      document.body.classList.add('ipl-teams-detail-open');
    }
    const xaiData = teamXAI[team.name] || teamXAI[team.short_name] || null;
    renderDetail(detail, team, createXAICard(xaiData));
    if (useFullscreen) {
      requestAnimationFrame(() => backBtn.focus());
      window.scrollTo({ top: 0, behavior: 'instant' });
    }
  }

  try {
    const xaiPaths = ['./data/xai/team_explainability.json', '/data/xai/team_explainability.json', './public/data/xai/team_explainability.json'];
    for (const p of xaiPaths) {
        try {
            const xaiRes = await fetch(p);
            if (xaiRes.ok) {
                teamXAI = await xaiRes.json();
                break;
            }
        } catch (e) {}
    }

    const bundlePaths = ['./data/ipl-teams-bundle.json', '/data/ipl-teams-bundle.json', './public/data/ipl-teams-bundle.json'];
    let res;
    for (const p of bundlePaths) {
        try {
            res = await fetch(p);
            if (res.ok) break;
        } catch (e) {}
    }

    if (!res || !res.ok) throw new Error("Could not find team bundle in any path.");
    const data = await res.json();
    const teams = data.teams || [];
    console.log(`[IPL Intelligence] Loaded ${teams.length} teams. Build: 2026-04-12-Immersive`);
    window.__IPL_TEAMS_LOADED__ = teams.length;
    if (!teams.length) throw new Error('No teams in bundle');

    selectedId = useFullscreen ? null : teams[0].id;

    renderGrid(
      grid,
      teams,
      (id) => {
        const t = teams.find((x) => x.id === id);
        if (t) openDetailView(t);
      },
      { picker: useFullscreen },
    );

    if (!useFullscreen) {
      const firstTeam = teams[0];
      const xaiData = teamXAI[firstTeam.name] || teamXAI[firstTeam.short_name] || null;
      renderDetail(detail, firstTeam, createXAICard(xaiData));
    }

    if (useFullscreen) {
      backBtn.addEventListener('click', closeDetailView);
      document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && !detailStage.hidden) {
          e.preventDefault();
          closeDetailView();
        }
      });
    }

    if (errEl) {
      errEl.classList.add('hidden');
      errEl.textContent = '';
    }
  } catch (e) {
    console.error('[IPL Teams]', e);
    grid.innerHTML = '';
    detail.innerHTML = '';
    if (useFullscreen) {
      detailStage.hidden = true;
      document.body.classList.remove('ipl-teams-detail-open');
    }
    if (errEl) {
      errEl.textContent = `Could not load IPL team profiles (${e.message}).`;
      errEl.classList.remove('hidden');
    }
  } finally {
    grid.removeAttribute('aria-busy');
  }
}
