# auto-generated by step2_inspect.py — do not edit manually
COL_MAP = {
    "batter":          'striker',
    "bowler":          'bowler',
    "batsman_runs":    'runs_off_bat',
    "total_runs":      'extras',
    "is_wicket":       'wicket_type',
    "is_wicket_flag":  False,
    "dismissal_kind":  'wicket_type',
    "season":          'season',
    "match_id":        'match_id',
    "innings":         'innings',
    "extras_kind":     None,
}
